# Creando arrays


In [51]:
import numpy as np
from IPython.display import display


In [64]:
a1 = np.asarray([1,2,3])
a2 = np.arange(10)
a3 = np.zeros((2,3,3))
a4 = np.ones ((2,3))
a5 = np.linspace(1,5,10)
a5


array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

# Dimension de un array

In [57]:
aD1 = np.asarray([2,3,4])
aD2 = np.asarray([[2,3,4]])

print(np.array_equiv(aD1,aD2))
print(np.array_equal(aD1,aD2))


True
False


# *Reshape*

In [56]:
#para hacer un reshape correctamente, ele*mult debe ser igual a ele
mult = 1
ele = aD1.shape[0]
new_dims = (mult, ele)
a = aD1.reshape(new_dims)
print(np.array_equiv(a,aD2))
print(np.array_equal(a,aD2))


True
True


# Acceder a elementos y slicing de arrays

In [98]:
array = np.asarray([[1,24,4],[4,5,6],[7,7,9]])
array2 = np.eye(5)
array2


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [100]:
array2[0,0:5]

array([ 1.,  0.,  0.,  0.,  0.])

# Operaciones con vectores

# Rendimiento

In [106]:
%%timeit
a = np.arange(10000000)
b = np.zeros(10000000)
i = 0
for el in a:
    b[i]=el+el
    i+=1
    

1.97 s ± 31.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [108]:
%%timeit
a+a

438 ns ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Estadistica y aleatoridad

In [112]:
a = np.arange(10)
display (a)
display (np.mean(a))
display (np.median(a))
display (np.mode(a))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.5

4.5

AttributeError: module 'numpy' has no attribute 'mode'

In [3]:
import pandas as pd

In [ ]:
wordpress = pd.re